alter table if exists public.assets
  add column if not exists public_ip_addresses text,
  add column if not exists device_type text,
  add column if not exists compliance_flags text,
  add column if not exists tags text[],
  add column if not exists environment text,
  add column if not exists qualys_vm_host_uid text,
  add column if not exists qualys_vm_host_link text,
  add column if not exists qualys_vm_host_integration text,
  add column if not exists servicenow_host_uid text,
  add column if not exists servicenow_host_link text,
  add column if not exists servicenow_host_integration text,
  add column if not exists aggregated_finding_risk numeric,
  add column if not exists exposure_modifier numeric,
  add column if not exists data_sensitivity_modifier numeric,
  add column if not exists environment_modifier numeric,
  add column if not exists asset_type_modifier numeric,
  add column if not exists asset_context_multiplier numeric,
  add column if not exists asset_risk_score numeric,
  add column if not exists scored_at timestamptz;

alter table if exists public.assets
  drop column if exists uid,
  drop column if exists dnsname,
  drop column if exists uuid,
  drop column if exists tracking_method,
  drop column if exists owner,
  drop column if exists service_team,
  drop column if exists division,
  drop column if exists it_sme,
  drop column if exists it_director,
  drop column if exists location,
  drop column if exists virtual_or_physical,
  drop column if exists compliance_status,
  drop column if exists asset_criticality,
  drop column if exists private_ip_addresses,
  drop column if exists last_authenticated_scan,
  drop column if exists last_scanned,
  drop column if exists exposure_score,
  drop column if exists business_criticality_score,
  drop column if exists data_sensitivity_score,
  drop column if exists asset_type_weight,
  drop column if exists is_public_facing,
  drop column if exists has_sensitive_data,
  drop column if exists crown_jewel_flag,
  drop column if exists internet_exposed_flag;
