create extension if not exists pgcrypto;

create table if not exists public.companies (
  id text primary key default gen_random_uuid()::text,
  name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_units (
  id text primary key default gen_random_uuid()::text,
  company_id text references public.companies(id) on delete set null,
  source_id text,
  name text not null,
  slug text not null unique,
  description text,
  owner text,
  crq_business_unit_risk_score numeric,
  crq_business_unit_priority_score numeric,
  crq_business_unit_business_service_count integer,
  crq_business_unit_application_count integer,
  crq_business_unit_asset_count integer,
  crq_business_unit_finding_count integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.business_services (
  id text primary key default gen_random_uuid()::text,
  business_unit_id text not null references public.business_units(id) on delete cascade,
  source_id text,
  name text not null,
  slug text not null,
  description text,
  criticality_label text,
  business_criticality_score integer,
  division text,
  manager text,
  crq_business_service_aggregated_application_risk numeric,
  crq_business_service_aggregated_direct_asset_risk numeric,
  crq_business_service_risk_score numeric,
  crq_business_service_priority_score numeric,
  crq_business_service_application_count integer,
  crq_business_service_asset_count integer,
  crq_business_service_finding_count integer,
  crq_business_service_scored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_business_services_business_unit_slug unique (business_unit_id, slug),
  constraint business_services_business_criticality_score_range
    check (
      business_criticality_score is null
      or business_criticality_score between 0 and 5
    )
);

create table if not exists public.applications (
  id text primary key default gen_random_uuid()::text,
  business_service_id text not null references public.business_services(id) on delete cascade,
  name text not null,
  slug text not null,
  description text,
  tags text[],
  first_seen_at timestamptz,
  crq_application_aggregated_asset_risk numeric,
  crq_application_compliance_score numeric,
  crq_application_risk_score numeric,
  crq_application_asset_count integer,
  crq_application_finding_count integer,
  crq_application_scored_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_applications_business_service_slug unique (business_service_id, slug)
);

create table if not exists public.assets (
  asset_id text primary key,
  hostname text,
  application text,
  business_service text,
  internal_or_external text,
  public_ip_addresses text,
  device_type text,
  category text,
  status text,
  compliance_flags text,
  pci boolean,
  pii boolean,
  tags text[],
  environment text,
  qualys_vm_host_id text,
  qualys_vm_host_link text,
  servicenow_host_id text,
  servicenow_host_link text,
  company_id text references public.companies(id) on delete set null,
  business_unit_id text references public.business_units(id) on delete set null,
  business_service_id text references public.business_services(id) on delete set null,
  application_id text references public.applications(id) on delete set null,
  crq_asset_aggregated_finding_risk numeric,
  crq_asset_exposure_score numeric,
  crq_asset_data_sensitivity_score numeric,
  crq_asset_environment_score numeric,
  crq_asset_type_score numeric,
  crq_asset_context_score numeric,
  crq_asset_risk_score numeric,
  crq_asset_finding_count integer,
  crq_asset_scored_at timestamptz
);

create table if not exists public.findings (
  id integer generated by default as identity primary key,
  asset_id text not null references public.assets(asset_id),
  finding_id text not null,
  finding_uid text,
  finding_name text,
  status text,
  cve_id text,
  brinqa_base_risk_score double precision,
  brinqa_risk_score double precision,
  first_found timestamp,
  last_found timestamp,
  age_in_days double precision,
  date_created timestamp,
  last_updated timestamp,
  crq_finding_score double precision,
  crq_finding_risk_band text,
  crq_finding_scored_at timestamptz,
  crq_finding_score_version text,
  crq_finding_cvss_score double precision,
  crq_finding_epss_score double precision,
  crq_finding_epss_percentile double precision,
  crq_finding_epss_multiplier double precision,
  crq_finding_is_kev boolean,
  crq_finding_kev_bonus double precision,
  crq_finding_age_days double precision,
  crq_finding_age_bonus double precision,
  crq_finding_notes text
);

create table if not exists public.epss_scores (
  cve text primary key,
  epss double precision,
  percentile double precision,
  date text,
  is_kev boolean,
  date_fetched timestamptz
);

create table if not exists public.kev (
  cve text primary key,
  date_added text,
  due_date text,
  vendor_project text,
  product text,
  vulnerability_name text,
  short_description text
);

create table if not exists public.nvd (
  cve text primary key,
  vuln_status text,
  published timestamptz,
  last_modified timestamptz,
  description text,
  cvss_score double precision,
  cvss_severity text,
  cvss_version text,
  cvss_vector text,
  cvss_exploitability_score double precision,
  cvss_impact_score double precision,
  attack_vector text,
  attack_complexity text,
  privileges_required text,
  user_interaction text,
  scope text,
  confidentiality_impact text,
  integrity_impact text,
  availability_impact text,
  primary_cwe_id text,
  primary_cwe_description text,
  weaknesses jsonb,
  affected_products jsonb,
  "references" jsonb,
  reference_groups jsonb,
  cisa_exploit_add date,
  cisa_action_due date,
  cisa_required_action text,
  cisa_vulnerability_name text
);

create index if not exists ix_companies_name on public.companies (name);
create index if not exists ix_business_units_company_id on public.business_units (company_id);
create index if not exists ix_business_units_source_id on public.business_units (source_id);
create index if not exists ix_business_units_name on public.business_units (name);
create index if not exists ix_business_units_slug on public.business_units (slug);
create index if not exists ix_business_units_crq_business_unit_risk_score on public.business_units (crq_business_unit_risk_score desc);
create index if not exists ix_business_units_crq_business_unit_priority_score on public.business_units (crq_business_unit_priority_score desc);

create index if not exists ix_business_services_business_unit_id on public.business_services (business_unit_id);
create index if not exists ix_business_services_source_id on public.business_services (source_id);
create index if not exists ix_business_services_name on public.business_services (name);
create index if not exists ix_business_services_slug on public.business_services (slug);
create index if not exists ix_business_services_crq_business_service_risk_score on public.business_services (crq_business_service_risk_score desc);
create index if not exists ix_business_services_crq_business_service_priority_score on public.business_services (crq_business_service_priority_score desc);

create index if not exists ix_applications_business_service_id on public.applications (business_service_id);
create index if not exists ix_applications_name on public.applications (name);
create index if not exists ix_applications_slug on public.applications (slug);
create index if not exists ix_applications_crq_application_risk_score on public.applications (crq_application_risk_score desc);

create index if not exists ix_assets_hostname on public.assets (hostname);
create index if not exists ix_assets_business_service on public.assets (business_service);
create index if not exists ix_assets_internal_or_external on public.assets (internal_or_external);
create index if not exists ix_assets_status on public.assets (status);
create index if not exists ix_assets_environment on public.assets (environment);
create index if not exists ix_assets_qualys_vm_host_id on public.assets (qualys_vm_host_id);
create index if not exists ix_assets_servicenow_host_id on public.assets (servicenow_host_id);
create index if not exists ix_assets_company_id on public.assets (company_id);
create index if not exists ix_assets_business_unit_id on public.assets (business_unit_id);
create index if not exists ix_assets_business_service_id on public.assets (business_service_id);
create index if not exists ix_assets_application_id on public.assets (application_id);
create index if not exists ix_assets_crq_asset_risk_score on public.assets (crq_asset_risk_score desc);
create index if not exists ix_assets_crq_asset_finding_count on public.assets (crq_asset_finding_count);

create index if not exists ix_findings_asset_id on public.findings (asset_id);
create index if not exists ix_findings_finding_id on public.findings (finding_id);
create index if not exists ix_findings_finding_uid on public.findings (finding_uid);
create index if not exists ix_findings_status on public.findings (status);
create index if not exists ix_findings_cve_id on public.findings (cve_id);
create index if not exists ix_findings_brinqa_risk_score on public.findings (brinqa_risk_score desc);
create index if not exists ix_findings_age_in_days on public.findings (age_in_days desc);
create index if not exists ix_findings_crq_finding_score on public.findings (crq_finding_score desc);
create index if not exists ix_findings_crq_finding_risk_band on public.findings (crq_finding_risk_band);
create index if not exists findings_asset_id_id_desc_idx on public.findings (asset_id, id desc);
create index if not exists findings_asset_id_age_desc_idx on public.findings (asset_id, age_in_days desc);
create index if not exists findings_asset_id_crq_finding_is_kev_idx on public.findings (asset_id, crq_finding_is_kev);
create index if not exists findings_asset_id_crq_finding_risk_band_idx on public.findings (asset_id, crq_finding_risk_band);
create index if not exists findings_asset_id_display_crq_finding_score_desc_idx
  on public.findings (asset_id, (coalesce(crq_finding_score, brinqa_risk_score)) desc, id desc);

create or replace function public.prevent_scoring_knowledge_base_delete()
returns trigger
language plpgsql
as $$
begin
  if current_setting('vulncontext.allow_knowledge_base_delete', true) = 'true' then
    if tg_op = 'DELETE' then
      return old;
    end if;
    return null;
  end if;

  raise exception
    'Refusing % on %.%. Set vulncontext.allow_knowledge_base_delete=true in the current transaction for intentional maintenance.',
    tg_op,
    tg_table_schema,
    tg_table_name;
end;
$$;

drop trigger if exists prevent_nvd_delete on public.nvd;
create trigger prevent_nvd_delete
before delete on public.nvd
for each row
execute function public.prevent_scoring_knowledge_base_delete();

drop trigger if exists prevent_nvd_truncate on public.nvd;
create trigger prevent_nvd_truncate
before truncate on public.nvd
for each statement
execute function public.prevent_scoring_knowledge_base_delete();

drop trigger if exists prevent_epss_scores_delete on public.epss_scores;
create trigger prevent_epss_scores_delete
before delete on public.epss_scores
for each row
execute function public.prevent_scoring_knowledge_base_delete();

drop trigger if exists prevent_epss_scores_truncate on public.epss_scores;
create trigger prevent_epss_scores_truncate
before truncate on public.epss_scores
for each statement
execute function public.prevent_scoring_knowledge_base_delete();

drop trigger if exists prevent_kev_delete on public.kev;
create trigger prevent_kev_delete
before delete on public.kev
for each row
execute function public.prevent_scoring_knowledge_base_delete();

drop trigger if exists prevent_kev_truncate on public.kev;
create trigger prevent_kev_truncate
before truncate on public.kev
for each statement
execute function public.prevent_scoring_knowledge_base_delete();

create or replace function public.update_is_kev()
returns void
language sql
as $$
  update public.epss_scores e
  set is_kev = exists (
    select 1
    from public.kev k
    where k.cve = e.cve
  );
$$;

alter table public.companies enable row level security;
alter table public.business_units enable row level security;
alter table public.business_services enable row level security;
alter table public.applications enable row level security;
alter table public.assets enable row level security;
alter table public.findings enable row level security;
alter table public.epss_scores enable row level security;
alter table public.kev enable row level security;
alter table public.nvd enable row level security;
